# Site settings
title: CI and CD with GitHub
description: A demo blog
email: training@github.com
twitter_username: nocomplexity
github_username:  nocomplexity
baseurl:
url: https://mike-cicd-workshop.herokuapp.com/
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
